# Generated by Django 5.0.6 on 2024-05-26 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applicant_behaviour',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_nationality',
            field=models.CharField(choices=[('Tanzanian', 'Tanzanian'), ('Other', 'Other')], default='Tanzanian', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cfdc_comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cfdc_name',
            field=models.CharField(default='No name', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cfdc_received_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cfdc_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='comments',
            field=models.TextField(default='No comment'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_result',
            field=models.CharField(default='good', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='other_comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='processed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='received_date_from_veo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicant',
            name='veo_name',
            field=models.CharField(default='No name', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='veo_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='weo_name',
            field=models.CharField(default='No name', max_length=200),
        ),
        migrations.AddField(
            model_name='applicant',
            name='weo_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=200),
        ),
    ]
