# Generated by Django 5.0.6 on 2024-05-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_applicant_business_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='business_duration',
        ),
    ]
